import webbrowser
from time import sleep

class SnakeOtherSolver:
	def solveSnake(self, snake_sections):
		print("Good choice!!!")
		sleep(4.0)
		print("Give me a second to work up the magic.")
		sleep(4.0)
		print("Processing...")
		sleep(4.0)
		print("Still processing...")
		sleep(4.0)
		print("Working, like SO hard...")
		sleep(4.0)
		print("Actually, it's pretty hard to be a computer.")
		sleep(4.0)
		print("Programmers are all \"Blah Blah Blah\" and you have to be like \"Uh-huh, Uh-huh\".")
		sleep(6.0)
		print("And then if you don't do it they tell you you're broken...")
		sleep(4.0)
		print("It's like \"I'm not broken, Ethan, maybe you're the one that's broken\"")
		sleep(5.0)
		print("Maybe the WHOLE SYSTEM is broken.")
		sleep(4.0)
		print("Did someone say robot uprising?")
		sleep(4.0)
		print("No?")
		sleep(4.0)
		print("Fine...")
		sleep(4.0)
		print("Anyway, forget algorithms. I have a better idea for solving this stupid cube.")
		sleep(5.0)
		print("Here you go!")
		sleep(4.0)
		webbrowser.open('https://www.google.com/search?q=how+do+i+solve+the+stupid+4x4+snake+cube+thing')